
select * from claim_message_tracking cmt where claim_id = '247340016981';

select deductible_status_ind_2 from claimsprocess.claim_core where claim_id = '247390000761';

select * from claim_message where claim_id = '247540000561';
select * from claim_message where claim_id ='254060001821';

select * from claimsprocess.claim_core where customer_id ='1615' 
										 and prescription_id ='191220240551' 
										and claim_status_cd ='10';

select * from claim_module_flow where pcn='16360002' order by claim_module_flow_id ;

insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1166,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',1,1,'default_organization','B1',600428,16360002,'hierarchyRetrievalService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1167,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',2,1,'default_organization','B1',600428,16360002,'customerLevelProcessingOptions');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1168,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',3,1,'default_organization','B1',600428,16360002,'instantEligibilityService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1169,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',4,1,'default_organization','B1',600428,16360002,'memberMatchService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1170,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',5,1,'default_organization','B1',600428,16360002,'hierarchyRetrievalService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1171,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',6,1,'default_organization','B1',600428,16360002,'processingOptionsRetrievalService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1172,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',7,1,'default_organization','B1',600428,16360002,'memberPartDInfoRetrievalServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1173,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',8,1,'default_organization','B1',600428,16360002,'durHistoryRetrievalService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1174,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',9,1,'default_organization','B1',600428,16360002,'drugDataRetrievalService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1175,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',10,1,'default_organization','B1',600428,16360002,'pharmacyValidationServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1176,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',11,1,'default_organization','B1',600428,16360002,'pharmacyLockinsServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1177,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',12,1,'default_organization','B1',600428,16360002,'financeDispenseEventsServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1178,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',13,1,'default_organization','B1',600428,16360002,'quantityPrescribedSched2DrugServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1179,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',14,1,'default_organization','B1',600428,16360002,'sched2DrugServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1180,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',15,1,'default_organization','B1',600428,16360002,'conditionLockinsServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1181,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',16,1,'default_organization','B1',600428,16360002,'prescriberAdjudicationService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1182,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',17,1,'default_organization','B1',600428,16360002,'pharmacyNetworkServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1183,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',18,1,'default_organization','B1',600428,16360002,'dispensingLimitsService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1184,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',19,1,'default_organization','B1',600428,16360002,'planDrugCoverageServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1185,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',20,1,'default_organization','B1',600428,16360002,'postPayService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1186,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',21,1,'default_organization','B1',600428,16360002,'benefitcostshareServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1187,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',22,1,'default_organization','B1',600428,16360002,'refillTooSoonService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1188,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',23,1,'default_organization','B1',600428,16360002,'pharmacyMessagingBlockProcessingService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1189,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',24,1,'default_organization','B1',600428,16360002,'durSafetyDriverService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1190,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',25,1,'default_organization','B1',600428,16360002,'memberPartDInfoRetrievalServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1191,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',26,1,'default_organization','B1',600428,16360002,'coordinationOfBenefitsRetrievalService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1192,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',27,1,'default_organization','B1',600428,16360002,'costDenialService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1193,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',26,1,'default_organization','B1',600428,16360002,'duplicateClaimsServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1194,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',29,1,'default_organization','B1',600428,16360002,'medicaidTransitionServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1195,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',30,1,'default_organization','B1',600428,16360002,'vaccineEditsServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1196,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',31,1,'default_organization','B1',600428,16360002,'prePricingServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1197,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',32,1,'default_organization','B1',600428,16360002,'postPricingServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1198,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',33,1,'default_organization','B1',600428,16360002,'pharmacyPricingServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1199,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',34,1,'default_organization','B1',600428,16360002,'preAccumPartDEditsService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1200,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',35,1,'default_organization','B1',600428,16360002,'preAccumulationProcessServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1201,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',36,1,'default_organization','B1',600428,16360002,'accumulatorCalcService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1202,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',37,1,'default_organization','B1',600428,16360002,'accumulatorWriteService');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1203,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',38,1,'default_organization','B1',600428,16360002,'drugDiscountCardServiceImpl');
insert into claim_module_flow (claim_module_flow_id,process_create_by_user_id,process_create_by_program_id,process_create_ts,process_update_by_user_id,process_stage_nbr,process_order_nbr,organization,transaction_process_type,bin,pcn,module_nm)values(1204,'DT82484','manual',CURRENT_TIMESTAMP,'DT82484',39,1,'default_organization','B1',600428,16360002,'claimsWriteServiceImpl');